### ISSUE TITLE
Add function to return string

### ISSUE THREAD

**Issue by CarsonF** [patarapolw/prettyprint#2]
Hey this is great, thanks for providing a library.

Could you add/export a function to return the string instead of logging it to console?

**Comment by patarapolw** [comment]
Would you want to keep the escape sequences (that changes console's color) intact? Otherwise, a lot of code have to changed.

**Comment by CarsonF** [comment]
Yeah I just want to pipe it through my logger object.

**Comment by patarapolw** [comment]
Since the project is exceedingly simple, you should really made a PR. Or, just simply just copy the code (which is already contained in a single file).

Anyways, I made it -- exported `ppRaw`.

**Comment by CarsonF** [comment]
It's not nothing, thanks!
